[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://app.netlify.com"
